CSharpPitchCounter/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CSharpPitchCounter.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        public int pitchCount;
        
        private int incrimentPitchCount(int pitchCount)
        {
            return pitchCount + 1;
        }

        private int decrimentPitchCount(int pitch)
        {
            return pitch - 1;
        }

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }

        public IActionResult OnPostIncrimentPitchCounter(int pitch)
        {
            pitchCount = incrimentPitchCount(pitch);
            return Page();
        }
        public IActionResult OnPostDecrimentPitchCounter(int pitch)
        {
            if (pitch > 0)
            {
                pitchCount = decrimentPitchCount(pitch);
            }
            return Page();
        }

    }
}

CSharpPitchCounter/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Pitch Count";
}

<div class="text-center ">
    <div class="ball">
        <h1>The Count: </h1>
        <h1>@Model.pitchCount</h1>
    </div>
    <form method="post" class="">
        <input value="@Model.pitchCount" name="pitch" hidden />
        <button asp-page-handler="IncrimentPitchCounter">Pitch</button>
        <button asp-page-handler="DecrimentPitchCounter">Remove Pitch</button>
    </form>
</div>
<style>
    .ball{
        width:250px;
        height: 250px;
        padding: 2rem;
        border-radius:125px;
        background-color: tan;
    }
</style>

CSharpPitchCounter/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CSharpPitchCounter</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - CSharpPitchCounter - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>